module.exports = {
	content: [
		"./src/**/*.{html,js,ts,jsx,tsx}",
		"app/**/*.{ts,tsx}",
		"components/**/*.{ts,tsx}",
	],
	theme: {
		extend: {
			colors: {
				brandlight: "var(--brandlight)",
				brandprimary: "var(--brandprimary)",
				brandsecondary: "var(--brandsecondary)",
				errorbg: "var(--errorbg)",
				errorcontent: "var(--errorcontent)",
				errordark: "var(--errordark)",
				issuebg: "var(--issuebg)",
				issuecontent: "var(--issuecontent)",
				neutralbg: "var(--neutralbg)",
				neutralcontent: "var(--neutralcontent)",
				"neutrallight-bg": "var(--neutrallight-bg)",
				neutralstroke: "var(--neutralstroke)",
				"neutralsub-content": "var(--neutralsub-content)",
				neutraltext: "var(--neutraltext)",
				neutralwhite: "var(--neutralwhite)",
				predictionbg: "var(--predictionbg)",
				predictioncontent: "var(--predictioncontent)",
				primarybrand: "var(--primarybrand)",
				scheduledbg: "var(--scheduledbg)",
				scheduledcontent: "var(--scheduledcontent)",
				"sec-text": "var(--sec-text)",
				successbg: "var(--successbg)",
				successcontent: "var(--successcontent)",
				successdark: "var(--successdark)",
				warningbg: "var(--warningbg)",
				warningcontent: "var(--warningcontent)",
				warninglight: "var(--warninglight)",
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
			},
			fontFamily: {
				"heading-h4": "var(--heading-h4-font-family)",
				"text-base-medium": "var(--text-base-medium-font-family)",
				"text-base-regular": "var(--text-base-regular-font-family)",
				"text-base-semibold": "var(--text-base-semibold-font-family)",
				"text-SM-normal": "var(--text-SM-normal-font-family)",
				"text-small-medium": "var(--text-small-medium-font-family)",
				"text-small-regular": "var(--text-small-regular-font-family)",
				sans: [
					"ui-sans-serif",
					"system-ui",
					"sans-serif",
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			keyframes: {
				"accordion-down": {
					from: { height: "0" },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: "0" },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
			},
		},
		container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
	},
	plugins: [],
	darkMode: ["class"],
};

